### ISSUE TITLE
Tests are failing on the latest commit

### ISSUE THREAD

**Issue by hamza1311** [krausest/js-framework-benchmark#1032]
We run tests in our CI (see [workflow](https://github.com/yewstack/yew/blob/master/.github/workflows/benchmark.yml)) and it has been failing recently.

The failures can see be seen in this pull request: https://github.com/yewstack/yew/pull/2651  
See: [failed action](https://github.com/yewstack/yew/runs/6247376284)

**Comment by krausest** [comment]
Sorry, I noticed that today too. Commit https://github.com/krausest/js-framework-benchmark/commit/e0b214bacc399d80619d663e831697296738b62e should fix it. Please let me know if it helps.

**Comment by hamza1311** [comment]
No, that didn't seem to fix. The workflow kept running for a long time. I cancelled it after it ran for over 45 minutes.

You can find the workflow here: https://github.com/yewstack/yew/runs/6248989263?check_suite_focus=true

**Comment by krausest** [comment]
Hmm. In the first log the following error was reported:
```
ERROR in run Benchmark: | browserType.launch: 
╔═════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Looks like you launched a headed browser without having a XServer running.                      ║
║ Set either 'headless: false' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║                                                                                                 ║
║ <3 Playwright Team                                                                              ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════╝
```
This should be fixed by my commit (I didn't set the headless argument correctly for playwright).

In the second workflow you can see that the tests are running and results for benchmark 01 and 02 completed successful and the benchmark was interrupted whilst running benchmark 03.
The reported benchmark results for the two benchmarks looks quite normal so I have no idea why it took that long and if it got stucked in benchmark 03.
(In other words: There was an error, but that was fixed and I've got no clue why it's now taking so long).

But I tried a workaround - just to see if it matters: I updated the benchmark configuration to use puppeteer again in https://github.com/krausest/js-framework-benchmark/commit/31f2b5e47e58c7c05c803215606703963add9dec. Does that help?

**Comment by hamza1311** [comment]
It did pull the correct commit - e0b214bacc399d80619d663e831697296738b62e (see [logs](https://github.com/yewstack/yew/runs/6248989263?check_suite_focus=true#step:3:469)). I just re-ran the workflow to see if that makes a difference. This time it checked out e0b214bacc399d80619d663e831697296738b62e (see [logs](https://github.com/yewstack/yew/runs/6249333764?check_suite_focus=true#step:3:469))

**Comment by hamza1311** [comment]
That commit fixed it: https://github.com/yewstack/yew/runs/6249333764?check_suite_focus=true

Not sure why playwright didn't work but it works now with puppeteer

**Comment by krausest** [comment]
I‘ve also no idea. Do you know how much RAM is available for your action?
As a permanent workaround I suggest adding a „driver“ argument such that you can choose puppeteer. I‘ll see when I can add that and then get back to you.

**Comment by hamza1311** [comment]
> I‘ve also no idea. Do you know how much RAM is available for your action?

It is default runner that GitHub provides for free for public repositories. The resources available can vary from run to run

**Comment by krausest** [comment]
The refactoring has landed. Currently it uses puppeteer by default, but I'll switch to playwright.
Please add `--runner puppeteer` as a command line flag to your `npm run bench` call.
