### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by ericpts** [krausest/js-framework-benchmark#128]
```
> npm run build

if(fs.statSync(name).isDirectory() && name[0] !== '.' && excludedDirectories.indexOf(name)==-1 && !skip) {
	                                                                                                   ^

ReferenceError: skip is not defined
    at /home/ericpts/work/js-framework-benchmark/build.js:8:101
    at arrayEach (/home/ericpts/work/js-framework-benchmark/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/home/ericpts/work/js-framework-benchmark/node_modules/lodash/lodash.js:9359:14)
    at Object.<anonymous> (/home/ericpts/work/js-framework-benchmark/build.js:7:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

**Comment by krausest** [comment]
Thanks for the heads up. Fixed by now.

**Comment by ericpts** [comment]
Hello!

Thanks for the fast reply.

Unfortunately it still does not compile, this time due to one of the frameworks included:
```
> js-framework-benchmark-aurelia@1.0.0 webpack /home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7
> cross-env BABEL_ENV=node ./node_modules/.bin/webpack "--progress" "--profile"

/home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/node_modules/extract-text-webpack-plugin/schema/validator.js:11
		throw new Error(ajv.errorsText());
		^

Error: data['sourceMap'] should NOT have additional properties
    at validate (/home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/node_modules/extract-text-webpack-plugin/schema/validator.js:11:9)
    at new ExtractTextPlugin (/home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/node_modules/extract-text-webpack-plugin/index.js:125:3)
    at Object.css (/home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/node_modules/@easy-webpack/config-css/src/index.ts:33:25)
    at generateConfig (/home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/node_modules/@easy-webpack/core/src/index.ts:26:40)
    at Object.<anonymous> (/home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/webpack.config.babel.js:74:14)
    at Module._compile (module.js:571:32)
    at loader (/home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireConfig (/home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/node_modules/webpack/bin/convert-argv.js:111:18)
    at /home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/node_modules/webpack/bin/convert-argv.js:124:17
    at Array.forEach (native)
    at module.exports (/home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/node_modules/webpack/bin/convert-argv.js:122:15)
    at Object.<anonymous> (/home/ericpts/work/js-framework-benchmark/aurelia-v1.0.7/node_modules/webpack/bin/webpack.js:141:40)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3


```

**Comment by krausest** [comment]
I get that too and have no idea how to fix it but by my default aurelia fix: Download the webpack skeleton again and replace package.json. Not sure if easy-webpack makes repeatable builds easier...
With aurelia 1.0.8 is works now on my machine. Does it work for you now?

If other frameworks cause problems you can always move their folder out of the js-framework-benchmark root and continue with the rest. Just let me know which causes problems and I'll see if I can fix it.
